@startuml
database "players"
[PlayerJPARepository] -("players"
getReferenceById - [PlayerJPARepository]

[PlayerService] -(getReferenceById
getPlayerById - [PlayerService]

[PlayerController] -(getPlayerById
@enduml