@startuml
database "players"
[PlayerController] --(getPlayerById
[PlayerController] --(savePlayer

[PlayerService] --(getReferenceById
[PlayerService] --(save
[PlayerService] --(findByUserNameOrEmail

getPlayerById -- [PlayerService]
savePlayer -- [PlayerService]

[PlayerJPARepository] --("players"
getReferenceById -- [PlayerJPARepository]
save -- [PlayerJPARepository]
findByUserNameOrEmail -- [PlayerJPARepository]

@enduml