@startuml
database "players"

[PlayerController] -(getPlayerById
[PlayerController] --(savePlayer

[PlayerService] --(getReferenceById
[PlayerService] --(save
getPlayerById --[PlayerService]
savePlayer -- [PlayerService]

[PlayerJPARepository] --("players"
getReferenceById -- [PlayerJPARepository]
save -- [PlayerJPARepository]


@enduml